#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

stream_direction_types = (
    'OUTPUT',
    'INPUT',
)

stream_pair_info_flags = (
    'OUTPUT',
    'INPUT',
    'DUPLEX',
)

stream_pair_error_types = (
    'FAILED',
    'DISCONNECTED',
)

types = {
    ALSARawmidi.StreamDirection:    stream_direction_types,
    ALSARawmidi.StreamPairInfoFlag: stream_pair_info_flags,
    ALSARawmidi.StreamPairError:    stream_pair_error_types,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
