#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target_type = ALSACtl.ElemInfoInteger
props = (
    'value-min',
    'value-max',
    'value-step',
    # From interfaces.
    'elem-id',
    'elem-type',
    'access',
    'owner',
    'value-count',
)
methods = (
    'new',
)
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
