#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.RemoveFilter
methods = (
    'new_with_dest_addr',
    'new_with_note_channel',
    'new_with_event_type',
    'new_with_note',
    'new_with_tag',
    'new_with_tick_time',
    'new_with_real_time',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
