#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

target_type = ALSARawmidi.SubstreamInfo
props = (
    'device-id',
    'subdevice-id',
    'direction',
    'card-id',
    'flags',
    'id',
    'name',
    'subdevice-name',
    'subdevices-count',
    'subdevices-avail',
)
methods = ()
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
