#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.QueueStatus
props = (
    'queue-id',
    'event-count',
    'running',
)
methods = (
    'new',
    'get_tick_time',
    'get_real_time',
)
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
