#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.EventDataQueue
methods = (
    'get_queue_id',
    'set_queue_id',
    'get_value_param',
    'set_value_param',
    'get_tick_time_param',
    'set_tick_time_param',
    'get_real_time_param',
    'set_real_time_param',
    'get_position_param',
    'set_position_param',
    'get_skew_param',
    'set_skew_param',
    'get_quadlet_param',
    'set_quadlet_param',
    'get_byte_param',
    'set_byte_param',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
