#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target_type = ALSACtl.ElemInfoBoolean
props = (
    'elem-id',
    'elem-type',
    'access',
    'owner',
    'value-count',
)
methods = (
    'new',
)
signals = ()

if not test_object(target_type, props, methods, signals):
    exit(ENXIO)
