#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.RealTimeEvent
methods = (
    'get_event',
    'get_time',
    'get_val',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
