#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.UserClient
props = (
    'client-id',
)
methods = (
    'new',
    'open',
    'get_protocol_version',
    'set_info',
    'get_info',
    'create_port',
    'create_port_at',
    'update_port',
    'delete_port',
    'set_pool',
    'get_pool',
    'schedule_event',
    'create_source',
    'operate_subscription',
    'create_queue',
    'delete_queue',
    'update_queue',
    'get_queue_usage',
    'set_queue_usage',
    'set_queue_tempo',
    'get_queue_tempo',
    'set_queue_timer',
    'get_queue_timer',
    'remove_events',
    'schedule_events',
)
vmethods = (
    'do_handle_event',
)
signals = (
    'handle-event',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
