#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target_type = ALSACtl.ElemInfoSingleArray
props = (
    'value-count',
)
methods = ()
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
