#!/usr/bin/env python3

from sys import exit

import gi
gi.require_version('ALSAHwdep', '0.0')
from gi.repository import ALSAHwdep

from helper import test_enums

iface_types = (
    'OPL2',
    'OPL3',
    'OPL4',
    'SB16CSP',
    'EMU10K1',
    'YSS225',
    'ICS2115',
    'SSCAPE',
    'VX',
    'MIXART',
    'USX2Y',
    'EMUX_WAVETABLE',
    'BLUETOOTH',
    'USX2Y_PCM',
    'PCXHR',
    'SB_RC',
    'HDA',
    'USB_STREAM',
    'FW_DICE',
    'FW_FIREWORKS',
    'FW_BEBOB',
    'FW_OXFW',
    'FW_DIGI00X',
    'FW_TASCAM',
    'LINE6',
    'FW_MOTU',
    'FW_FIREFACE',
)

device_common_error_types = (
    'FAILED',
    'IS_OPENED',
    'IS_NOT_OPENED',
    'IS_USED',
    'IS_NOT_SUPPORTED',
    'IS_DISCONNECTED',
)

types = {
    ALSAHwdep.IfaceType:    iface_types,
    ALSAHwdep.DeviceCommonError: device_common_error_types,
}

for target_type, enumerations in types.items():
    if not test_enums(target_type, enumerations):
        exit(1)
