#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.SystemInfo()
props = (
    'maximum-queue-count',
    'maximum-client-count',
    'maximum-port-count',
    'maximum-channel-count',
    'current-client-count',
    'current-queue-count',
)
methods = ()
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
