#!/usr/bin/env python3

from sys import exit

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

from helper import test_enums

stream_direction_types = (
    'OUTPUT',
    'INPUT',
)

stream_pair_info_flags = (
    'OUTPUT',
    'INPUT',
    'DUPLEX',
)

stream_pair_error_types = (
    'FAILED',
    'DISCONNECTED',
)

types = {
    ALSARawmidi.StreamDirection:    stream_direction_types,
    ALSARawmidi.StreamPairInfoFlag: stream_pair_info_flags,
    ALSARawmidi.StreamPairError:    stream_pair_error_types,
}

for target_type, enumerations in types.items():
    if not test_enums(target_type, enumerations):
        exit(1)
