#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.ClientInfo()
props = (
    'client-id',
    'type',
    'name',
    'filter-attributes',
    'use-filter',
    'port-count',
    'lost-count',
    'card-id',
    'process-id',
)
methods = (
    'new',
    'set_event_filter',
    'get_event_filter',
)
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
