#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSAHwdep', '0.0')
from gi.repository import ALSAHwdep

target = ALSAHwdep.DeviceInfo()
props = (
    'device-id',
    'card-id',
    'id',
    'name',
    'iface',
)
methods = ()
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
