#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target = ALSATimer.UserInstance()
props = ()
methods = (
    'new',
    'open',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
