#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target = ALSATimer.UserInstance()
props = ()
methods = (
    'new',
    'open',
    'attach',
    'attach_as_slave',
    'get_info',
    'set_params',
    'get_status',
    'create_source',
    'do_handle_event',
)
signals = (
    'handle-event',
)

if not test(target, props, methods, signals):
    exit(ENXIO)
