#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

target = ALSARawmidi.StreamPair()
props = (
    'devnode',
)
methods = (
    'new',
    'open',
    'get_substream_info',
    'set_substream_params',
    'get_substream_status',
    'read_from_substream',
    'write_to_substream',
    'drain_substream',
    'drop_substream',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
