#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.ElemInfoInteger64.new()
props = (
    'elem-id',
    'elem-type',
    'access',
    'owner',
    'value-count',
    'value-min',
    'value-max',
    'value-step',
)
methods = (
    'new',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
