#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.InstanceStatus
props = (
    'interval',
    'lost',
    'overrun',
    'queue-size',
)
methods = (
    'new',
    'get_time',
)
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
