#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target_type = ALSACtl.Card
props = (
    'devnode',
    'subscribed',
)
methods = (
    'new',
    'open',
    'get_protocol_version',
    'get_info',
    'get_elem_id_list',
    'lock_elem',
    'get_elem_info',
    'write_elem_tlv',
    'read_elem_tlv',
    'command_elem_tlv',
    'add_elems',
    'replace_elems',
    'remove_elems',
    'write_elem_value',
    'read_elem_value',
    'create_source',
)
vmethods = (
    'do_handle_elem_event',
    'do_handle_disconnection',
)
signals = (
    'handle-elem-event',
    'handle-disconnection',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
