#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

from helper import test_functions

entries = {
    ALSARawmidi: (
        'get_device_id_list',
        'get_rawmidi_sysname',
        'get_rawmidi_devnode',
        'get_subdevice_id_list',
        'get_substream_info',
    ),
    ALSARawmidi.StreamPairError: (
        'quark',
    ),
}

for target_type, functions in entries.items():
    if not test_functions(target_type, functions):
        exit(ENXIO)
