#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.UserInstance
props = ()
methods = (
    'new',
    'open',
    'get_protocol_version',
    'choose_event_type',
    'attach',
    'attach_as_slave',
    'get_info',
    'set_params',
    'get_status',
    'create_source',
    'do_handle_tick_event',
    'do_handle_tstamp_event',
    'do_handle_disconnection',
    'start',
    'stop',
    'pause',
    'continue_',
)
signals = (
    'handle-tick-event',
    'handle-tstamp-event',
    'handle-disconnection',
)

if not test_object(target_type, props, methods, signals):
    exit(ENXIO)
