#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target_type = ALSACtl.ElemId
methods = (
    'get_numid',
    'get_iface',
    'get_device_id',
    'get_subdevice_id',
    'get_name',
    'get_index',
    'equal',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
