#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.ElemInfo
props = (
    'elem-id',
    'type',
    'access',
    'owner',
)
methods = (
    'get_int_data',
    'set_int_data',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
