#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.UserClient()
props = (
    'client-id',
)
methods = (
    'new',
    'open',
    'set_info',
    'get_info',
    'create_port',
    'update_port',
    'delete_port',
    'set_pool',
    'get_pool',
    'schedule_event',
    'create_source',
    'operate_subscription',
    'create_queue',
    'delete_queue',
    'update_queue',
    'get_queue_usage',
    'set_queue_usage',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
