#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.EventCntr()
props = ()
methods = (
    'new',
    'count_events',
    'calculate_pool_consumption',
    'get_event_type',
    'set_event_type',
    'get_tstamp_mode',
    'set_tstamp_mode',
    'get_time_mode',
    'set_time_mode',
    'get_length_mode',
    'get_priority_mode',
    'set_priority_mode',
    'get_tag',
    'set_tag',
    'get_queue_id',
    'set_queue_id',
    'get_tstamp',
    'set_tstamp',
    'get_dst',
    'set_dst',
    'get_src',
    'set_src',
    'get_note_data',
    'set_note_data',
    'get_ctl_data',
    'set_ctl_data',
    'get_byte_data',
    'set_byte_data',
    'get_quadlet_data',
    'set_quadlet_data',
    'get_blob_data',
    'set_blob_data',
    'get_queue_data',
    'set_queue_data',
    'get_tstamp_data',
    'set_tstamp_data',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)

