#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.SystemInfo
props = (
    'maximum-queue-count',
    'maximum-client-count',
    'maximum-port-count',
    'maximum-channel-count',
    'current-client-count',
    'current-queue-count',
)
methods = ()
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
