#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.ElemValue()
props = (
    'elem-id',
)
props = ()
methods = (
    'set_bool',
    'get_bool',
    'set_int',
    'get_int',
    'set_enum',
    'get_enum',
    'set_bytes',
    'get_bytes',
    'set_iec60958',
    'get_iec60958',
    'set_int64',
    'get_int64',
    'equal',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
