#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target = ALSATimer.InstanceParams()
props = (
    'flags',
    'interval',
    'queue-size',
)
methods = (
    'new',
    'set_event_filter',
    'get_event_filter',
)
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
