#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.EventDataNote
methods = (
    'get_channel',
    'set_channel',
    'get_note',
    'set_note',
    'get_velocity',
    'set_velocity',
    'get_off_velocity',
    'set_off_velocity',
    'get_duration',
    'set_duration',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
