#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.EventDataConnect
methods = (
    'get_src',
    'set_src',
    'get_dst',
    'set_dst',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
