#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.PortInfo
props = (
    'name',
    'caps',
    'attrs',
    'midi-channels',
    'midi-voices',
    'synth-voices',
    'read-users',
    'write-users',
    'tstamp-overwrite',
    'tstamp-mode',
    'queue-id',
)
methods = (
    'new',
)
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
