#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

from helper import test_functions

entries = {
    ALSATimer: (
        'get_sysname',
        'get_devnode',
        'get_device_id_list',
        'get_device_info',
        'get_device_status',
        'set_device_params',
        'get_real_time_clock_id',
    ),
    ALSATimer.UserInstanceError: (
        'quark',
    ),
}

for target_type, functions in entries.items():
    if not test_functions(target_type, functions):
        exit(ENXIO)
