#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.TickTimeEvent
methods = (
    'get_resolution',
    'get_count',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
