#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.QueueInfo()
props = (
    'queue-id',
    'client-id',
    'locked',
    'name',
)
methods = (
    'new',
)
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
