#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.DeviceParams
props = (
    'period-numerator',
    'period-denominator',
)
methods = (
    'new',
)
signals = ()

if not test_object(target_type, props, methods, signals):
    exit(ENXIO)
