#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSAHwdep', '0.0')
from gi.repository import ALSAHwdep

target_type = ALSAHwdep.DeviceCommon
props = ()
methods = (
    'open',
    'get_protocol_version',
    'get_device_info',
    'create_source',
)
vmethods = (
    'do_open',
    'do_get_protocol_version',
    'do_get_device_info',
    'do_create_source',
    'do_handle_disconnection',
)
signals = (
    'handle-disconnection',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
