#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

target = ALSARawmidi.SubstreamInfo()
props = (
    'device-id',
    'subdevice-id',
    'direction',
    'card-id',
    'flags',
    'id',
    'name',
    'subdevice-name',
    'subdevices-count',
    'subdevices-avail',
)
methods = ()
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
