#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.ElemInfoIec60958.new()
props = (
    'elem-id',
    'elem-type',
    'access',
    'owner',
)
methods = (
    'new',
)
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
