#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

target = ALSARawmidi.StreamPair()
props = (
    'devnode',
)
methods = (
    'new',
    'open',
    'get_protocol_version',
    'get_substream_info',
    'set_substream_params',
    'get_substream_status',
    'read_from_substream',
    'write_to_substream',
    'drain_substream',
    'drop_substream',
    'create_source',
    'do_handle_messages',
    'do_handle_disconnection',
)
signals = (
    'handle-messages',
    'handle-disconnection',
)

if not test_object(target, props, methods, signals):
    exit(ENXIO)
