#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.DeviceId
methods = (
    'new',
    'get_class',
    'get_card_id',
    'get_device_id',
    'get_subdevice_id',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
