#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSAHwdep', '0.0')
from gi.repository import ALSAHwdep

iface_types = (
    'OPL2',
    'OPL3',
    'OPL4',
    'SB16CSP',
    'EMU10K1',
    'YSS225',
    'ICS2115',
    'SSCAPE',
    'VX',
    'MIXART',
    'USX2Y',
    'EMUX_WAVETABLE',
    'BLUETOOTH',
    'USX2Y_PCM',
    'PCXHR',
    'SB_RC',
    'HDA',
    'USB_STREAM',
    'FW_DICE',
    'FW_FIREWORKS',
    'FW_BEBOB',
    'FW_OXFW',
    'FW_DIGI00X',
    'FW_TASCAM',
    'LINE6',
    'FW_MOTU',
    'FW_FIREFACE',
)

types = {
    ALSAHwdep.IfaceType:    iface_types,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
