#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.ElemId()
props = ()
methods = (
    'get_numid',
    'get_iface',
    'get_device',
    'get_subdevice',
    'get_name',
    'get_index',
    'equals',
)
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
