#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target_type = ALSATimer.DeviceStatus
props = (
    'resolution',
    'resolution-numerator',
    'resolution-denominator',
)
methods = (
    'new',
)
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
