#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.EventFixed()
props = (
    'result-data',
    'note-data',
    'ctl-data',
    'queue-data',
    'addr-data',
    'connect-data',
)
methods = (
    'new',
    'get_byte_data',
    'set_byte_data',
    'get_quadlet_data',
    'set_quadlet_data',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)

