#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target_type = ALSASeq.Event
methods = (
    'new',
    'get_event_type',
    'get_length_mode',
    'get_tstamp_mode',
    'get_time_mode',
    'set_time_mode',
    'get_priority_mode',
    'set_priority_mode',
    'get_tag',
    'set_tag',
    'get_queue_id',
    'set_queue_id',
    'get_source',
    'set_source',
    'get_destination',
    'set_destination',
    'get_tick_time',
    'set_tick_time',
    'get_real_time',
    'set_real_time',
    'get_note_data',
    'set_note_data',
    'get_ctl_data',
    'set_ctl_data',
    'get_byte_data',
    'set_byte_data',
    'get_quadlet_data',
    'set_quadlet_data',
    'get_blob_data',
    'set_blob_data',
    'get_pointer_data',
    'set_pointer_data',
    'get_queue_data',
    'set_queue_data',
    'get_tick_time_data',
    'set_tick_time_data',
    'get_real_time_data',
    'set_real_time_data',
    'get_addr_data',
    'set_addr_data',
    'get_connect_data',
    'set_connect_data',
    'get_result_data',
    'set_result_data',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
