#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.Card()
props = (
    'devnode',
)
methods = (
    'new',
    'open',
    'get_info',
    'get_elem_id_list',
    'lock_elem',
    'get_elem_info',
    'write_elem_tlv',
    'read_elem_tlv',
    'command_elem_tlv',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
