#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSAHwdep', '0.0')
from gi.repository import ALSAHwdep

target = ALSAHwdep.DeviceInfo()
props = ()
methods = ()
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)
