#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.ClientPool()
props = (
    'client-id',
    'output-pool',
    'input-pool',
    'output-room',
    'output-free',
    'input-free',
)
methods = ()
signals = ()

if not test_object(target, props, methods, signals):
    exit(ENXIO)
