#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

from helper import test_functions

entries = {
    ALSASeq: (
        'get_seq_sysname',
        'get_seq_devnode',
        'get_system_info',
        'get_client_id_list',
        'get_client_info',
        'get_port_id_list',
        'get_port_info',
        'get_client_pool',
        'get_subscription_list',
        'get_queue_id_list',
        'get_queue_info_by_id',
        'get_queue_info_by_name',
        'get_queue_status',
    ),
    ALSASeq.UserClientError: (
        'quark',
    ),
}

for target_type, functions in entries.items():
    if not test_functions(target_type, functions):
        exit(ENXIO)
