#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

target_type = ALSARawmidi.SubstreamStatus
props = (
    'avail',
    'xruns',
)
methods = (
    'new',
)
vmethods = ()
signals = ()

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
