#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.EventVariable()
props = ()
methods = (
    'new',
    'get_data',
    'set_data',
)
signals = ()

if not test(target, props, methods, signals):
    exit(ENXIO)

